version: '3.9'

services:

  db:
    build:
      context: db/postgresql_multipledb
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: pass
      POSTGRES_MULTIPLE_DATABASES: article_db,user_db,comment_db
    ports:
      - 5432:5432

  graphql:
    build:
      context: .
      dockerfile: graphql/Dockerfile
      args:
        BUILD_FLAG: ""
        BUILD_TARGET: debug
        ENV: dev
        ARTICLE_ENDPOINT: http://article
        USER_ENDPOINT: http://user
        COMMENT_ENDPOINT: http://comment

    depends_on:
      - "article"
      - "user"
      - "comment"

    links:
      - "user:user"
      - "article:article"
      - "comment:comment"
    ports:
      - 5010:5000

  article:
    build:
      context: .
      dockerfile: article/Dockerfile
      args:
        BUILD_FLAG: ""
        BUILD_TARGET: debug
        ENV: dev
        DATABASE_URL: postgres://db_user:pass@db:5432/article_db
    depends_on:
      - "db"
    links:
      - "db:db"
    ports:
      - 5011:5000

  user:
    build:
      context: .
      dockerfile: user/Dockerfile
      args:
        BUILD_FLAG: ""
        BUILD_TARGET: debug
        ENV: dev
        DATABASE_URL: postgres://db_user:pass@db:5432/user_db
    depends_on:
      - "db"
    links:
      - "db:db"
    ports:
      - 5012:5000


  comment:
    build:
      context: .
      dockerfile: comment/Dockerfile
      args:
        BUILD_FLAG: ""
        BUILD_TARGET: debug
        ENV: dev
        DATABASE_URL: postgres://db_user:pass@db:5432/comment_db
    depends_on:
      - "db"
    links:
      - "db:db"
    ports:
      - 5013:5000

