version: '3.9'

services:

  db:
    build:
      context: db/postgresql_multipledb
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: pass
      POSTGRES_MULTIPLE_DATABASES: article_db,user_db,comment_db
    ports:
      - 5432:5432

  graphql:
    build:
      context: .
      dockerfile: graphql/Dockerfile
      args:
        BUILD_FLAG: ""
        BUILD_TARGET: debug
        ENV: dev
    ports:
      - 5010:5000

