version: '3.9'

services:

  db:
    build:
      context: docker/postgresql_multipledb
      dockerfile: docker/postgresql_multipledb/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: pass
      POSTGRES_MULTIPLE_DATABASES: article_db,user_db,comment_db
    ports:
      - 5432:5432
