version: '3.9'

services:

  db:
    build:
      context: db/postgresql_multipledb
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: pass
      POSTGRES_MULTIPLE_DATABASES: article_db,user_db,comment_db
    ports:
      - 5432:5432

  graphql:
    build:
      context: .
      dockerfile: graphql/Dockerfile
      args:
        BUILD_FLAG: ""
        BUILD_TARGET: debug
        ENV: dev
    depends_on:
      - "article"
    ports:
      - 5010:5000

  article:
    build:
      context: .
      dockerfile: article/Dockerfile
      args:
        BUILD_FLAG: ""
        BUILD_TARGET: debug
        ENV: dev
        DATABASE_URL: postgres://db_user:pass@db:5432/article_db
    depends_on:
      - "db"
    links:
      - "db:db"
    ports:
      - 5011:5000

